#!/usr/bin/env python3
"""
Build the screening universe from an authoritative external list instead of
hand-typing tickers. This is the "wide mouth" of the two-stage funnel: a
large, refreshable base of real candidates, not a wishlist.

Source (free, no key, reachable through the agent proxy):
  - S&P 500 constituents: the `datasets/s-and-p-500-companies` GitHub CSV,
    which carries Symbol, Security (name), GICS Sector, and CIK. The CIK is
    gold here — it lets fetch_fundamentals.py hit SEC EDGAR directly without
    a ticker->CIK lookup.

Design rules:
  - NEVER hand-types tickers from model memory (that is exactly the
    hallucination this system exists to prevent). The S&P 500 category is
    fetched; if the fetch fails, the existing universe.json is left untouched.
  - PRESERVES every user-maintained ("manual") category already in
    universe.json — Nordic large caps, broad index ETFs, crypto proxies,
    and any hand-curated theme lists. Those come from sources the proxy
    blocks (Wikipedia/Nasdaq Nordic), so they stay user-maintained.
  - Writes a `metadata` map (name, sector, cik, source) the ranker consumes,
    and records provenance under `auto_generated`.

Usage:
  python scripts/build_universe.py            # refresh the sp500 category
  python scripts/build_universe.py --dry-run  # show what would change
"""
import argparse
import csv
import io
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone

UNIVERSE_PATH = "data/cache/universe.json"
SP500_CSV_URL = (
    "https://raw.githubusercontent.com/datasets/"
    "s-and-p-500-companies/main/data/constituents.csv"
)
# Categories that come from sources the proxy blocks — never overwritten here.
MANUAL_CATEGORIES = {
    "us_mega_cap", "us_quality_dividend", "semis_and_ai_infra",
    "nordic_large_cap", "broad_index_etfs", "crypto_usd_proxies",
    "europe_large_cap",
}


def fetch_sp500():
    """Return (tickers, metadata) from the GitHub constituents CSV, or raise."""
    req = urllib.request.Request(
        SP500_CSV_URL, headers={"User-Agent": "finance-council research (seguifelix@gmail.com)"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        text = resp.read().decode()
    rows = list(csv.DictReader(io.StringIO(text)))
    if len(rows) < 400:
        raise RuntimeError(f"sp500 CSV returned only {len(rows)} rows — refusing to trust it")
    tickers, meta = [], {}
    for r in rows:
        sym = (r.get("Symbol") or "").strip()
        if not sym:
            continue
        cik = (r.get("CIK") or "").strip()
        meta[sym] = {
            "name": (r.get("Security") or "").strip(),
            "sector": (r.get("GICS Sector") or "").strip() or None,
            "cik": cik.zfill(10) if cik.isdigit() else None,
            "source": "sp500_github",
        }
        tickers.append(sym)
    return sorted(set(tickers)), meta


def load_existing():
    if os.path.exists(UNIVERSE_PATH):
        with open(UNIVERSE_PATH) as f:
            return json.load(f)
    return {}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    existing = load_existing()
    old_cats = existing.get("categories", {})

    try:
        sp_tickers, sp_meta = fetch_sp500()
    except Exception as e:
        sys.exit(f"S&P 500 fetch failed ({e}); universe.json left unchanged.")

    # Preserve every manual category verbatim; refresh only sp500.
    categories = {c: old_cats[c] for c in old_cats if c in MANUAL_CATEGORIES}
    categories["sp500"] = sp_tickers

    # Metadata: keep any existing metadata for manual tickers, refresh sp500.
    metadata = dict(existing.get("metadata", {}))
    metadata.update(sp_meta)

    result = {
        "note": (
            "Screening universe. The `sp500` category is AUTO-GENERATED by "
            "scripts/build_universe.py from a public constituents CSV — do not "
            "hand-edit it, re-run the script to refresh. All other categories "
            "are USER-MAINTAINED (sources the proxy blocks); add/remove freely. "
            "`metadata` carries name/sector/cik/source for the ranker. Nordic "
            "crypto certificate tickers must be verified on Avanza before use."
        ),
        "last_updated": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "auto_generated": {
            "sp500": {
                "count": len(sp_tickers),
                "source": SP500_CSV_URL,
                "refreshed_utc": datetime.now(timezone.utc).isoformat(),
            }
        },
        "manual_categories": sorted(c for c in categories if c != "sp500"),
        "categories": categories,
        "category_notes": existing.get("category_notes", {}),
        "metadata": metadata,
    }

    added = set(sp_tickers) - set(old_cats.get("sp500", []))
    removed = set(old_cats.get("sp500", [])) - set(sp_tickers)
    print(f"sp500: {len(sp_tickers)} tickers (+{len(added)} / -{len(removed)} vs previous)")
    print(f"manual categories preserved: {result['manual_categories']}")

    if args.dry_run:
        print("dry-run — not writing.")
        return

    with open(UNIVERSE_PATH, "w") as f:
        json.dump(result, f, indent=2)
    print(f"Wrote {UNIVERSE_PATH}")


if __name__ == "__main__":
    main()
